Grade gut
BojanTRB/nationsLeague pull request #11
Opened 2023-05-17 20:20 UTC by markolkc

2023-05-18 06:35 UTC, schletz requested changes
JSON Schema missing, see https://github.com/schletz/Dbi2Sem/blob/master/projekt_sommersemester.md#bewertung-befriedigend:

> Ergänzung des Modelles um ein Entity – Attribute – Value Modell (siehe https://github.com/schletz/Dbi2Sem/tree/master/34_EntityAttribute). Es kann wahlweise mit Entities modelliert oder als JSON Spalte angegeben werden. Bei einer JSON Spalte ist ein JSON Schema (https://json-schema.org/learn/getting-started-step-by-step#defining-the-properties) zu definieren.

Write your schema in _game_value_schema.json_

2023-05-18 06:35 UTC, schletz commented on create_db.sql
> +SELECT
Remove this select (I think this was for debugging)

2023-05-19 09:11 UTC, markolkc commented
schema and data for the schema done; sql updated

2023-05-22 12:33 UTC, schletz requested changes
Your INSERT Statements
```sql
INSERT INTO Game VALUES (3, 2, '{"gameday": 1, "gamedate": "2023-05-11"}');
INSERT INTO Game VALUES (1, 4, '{"gameday": 2, "gamedate": "2023-05-12"}');
INSERT INTO Game VALUES (6, 5, '{"gameday": 3, "gamedate": "2023-05-13"}');
INSERT INTO Game VALUES (7, 9, '{"gameday": 4, "gamedate": "2023-05-14"}');
INSERT INTO Game VALUES (10, 8, '{"gameday": 5, "gamedate": "2023-05-15"}');
INSERT INTO Game VALUES (11, 12, '{"gameday": 6, "gamedate": "2023-05-16"}');
```
does not validate against your schema in *game_value_schema.json* (*Required properties are missing from object: Id, HomeTeam, AwayTeam, GameDate.*)

Your data in *data_game_value_schema.json* does not validate against your schema (check each object in your array).

Check https://www.jsonschemavalidator.net if your json is valid.

2023-05-23 04:33 UTC, schletz requested changes
Your view *GameView* doesn't work anymore because JSON keys are case sensitive (returns always NULL for gameday and gamedate).

2023-05-23 04:38 UTC, schletz approved these changes

2023-05-23 04:41 UTC, merged

2023-05-23 04:41 UTC, schletz commented
Good work, you can start with branch _sehr gut_. 

For sehr gut you can choose: You can map a view to ef core (as described in https://github.com/schletz/Dbi2Sem/blob/master/projekt_sommersemester.md#bewertung-sehr-gut) or you can do the following, if you are interested in.

Create a .NET 7 (not 6) Program and import your model with ef power tools (or another scaffolder). Use inheritance for your vehicle types and map the discriminator to your Discriminator column.

You can map your JSON column to a C# class, see https://www.youtube.com/watch?v=Nqd3snxmILE

Create a unittest to add some vehicle with some additional infos and try to query vehicles with specified attributes.