Grade genuegend
BojanTRB/nationsLeague pull request #7
Opened 2023-04-26 10:11 UTC by BojanTRB

2023-04-27 17:29 UTC, schletz requested changes
Some changes are not done in all files (logical + physical + dump must be consistent). See comments in the code review. Please check for consistency after making changes.
Instead of committing multiple "fix xx.sql" you can use an amend commit, see https://github.com/schletz/Pos3xhif/blob/master/06%20Git/06_history.md#den-letzten-commit-neu-schreiben-der-amend-commit

2023-04-27 17:29 UTC, schletz commented on create_db.sql
> +	[Name] VARCHAR(200) NOT NULL,
Split fields.

2023-04-27 17:29 UTC, schletz commented on create_db.sql
> +	[Name] VARCHAR(200) NOT NULL,
Split fields.

2023-04-27 17:29 UTC, schletz commented on er_logical.puml
> +    HomeTeam : INTEGER <<FK>>
add star for NOT NULL

2023-04-27 17:29 UTC, schletz commented on er_logical.puml
> +    AwayTeam : INTEGER <<FK>>
add star for NOT NULL

2023-04-27 17:29 UTC, schletz commented on create_db.sql
> +	UNIQUE (Name)
To remove

2023-04-27 17:29 UTC, schletz commented on create_db.sql
> +	UNIQUE (Name)
To remove

2023-04-27 17:29 UTC, schletz commented on create_db.sql
> +	TrainerId INTEGER,
Why nullable?

2023-04-27 17:29 UTC, schletz commented on create_db.sql
> +	TeamId INTEGER,
Why nullable?

2023-04-27 17:29 UTC, schletz commented on er_logical.puml
> +    TrainerId : INTEGER <<FK>>
Why nullable?

2023-04-27 17:29 UTC, schletz commented on er_logical.puml
> +    TeamId : INTEGER <<FK>>
Why nullable?

2023-05-03 09:01 UTC, BojanTRB commented
Amended to last commit and waiting for a new review.

2023-05-03 11:09 UTC, schletz approved these changes

2023-05-03 11:09 UTC, merged